name: Cypress Automation

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: E2E Chrome
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
